//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_MoHinhMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int SubCategoryNumber { get; set; }
        public int CategoryNumber { get; set; }
        public string SubCategoryName { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
